# yaml-language-server: $schema=https://raw.githubusercontent.com/xenOs76/https-wrench/refs/heads/main/https-wrench.schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
---
debug: false
verbose: true
requests:
  - name: httpBunCom
    transportOverrideUrl: https://cat.httpbun.com:443
    clientTimeout: 3
    userAgent: wrench-httpbun-ua

    requestHeaders:
      - key: x-custom-header
        value: custom-header-value
      - key: x-api-key
        value: api-value

    printResponseBody: true
    printResponseHeaders: true
    responseHeadersFilter:
      - X-Powered-By
      - Via
      - Content-Type

    hosts:
      - name: httpbun.com
        uriList:
          - /headers
          - /status/302
          - /status/404
          - /status/503
