---
on:
  push:
    paths:
      - "cmd/**"
      - "internal/**"
      - "pkg/**"
      - "*.go"
      - "go.*"
jobs:
  govulncheck_job:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: 1.24
          go-package: ./...
          work-dir: .
